server:
  port: 8005
spring:
  application:
    name: sms-service
  rabbitmq:
    # 主机地址
    host: 192.168.136.103
    # 用户名、密码
    username: leyou
    password: leyou
    # 虚拟主机
    virtual-host: /leyou
  redis:
    host: 192.168.136.103
    port: 6379
ly:
  sms:
    accessKeyID: XXXXXXXXXX
    accessKeySecret: XXXXXXXXXX
    signName: XX
    verifyCodeTemplate: SMS_XXXXXXX
