server:
  port: 8007
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
ly:
  jwt:
    secret: https://www.imxushuai.com # 登录校验的密钥
    pubKeyPath: C:\\key\\rsa.pub # 公钥地址
    priKeyPath: C:\\key\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN